services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: hookrelay
      POSTGRES_PASSWORD: hookrelay
      POSTGRES_DB: hookrelay
    ports:
      - "54320:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../migrations:/docker-entrypoint-initdb.d

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  hookrelay:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      HOOKRELAY_DATABASE_DSN: "postgresql://hookrelay:hookrelay@postgres:5432/hookrelay?sslmode=disable"
      HOOKRELAY_REDIS_ADDR: "redis:6379"
    depends_on:
      - postgres
      - redis

  prometheus:
    image: prom/prometheus:v2.51.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:10.4.0
    ports:
      - "30000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - grafanadata:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  pgdata:
  grafanadata:
